name: Build docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - docs
  workflow_dispatch:

jobs:

  build-and-upload-artifact:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python 3.9
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'setuptools<50.0'
          python -m pip install .[testing,docs]

      - name: Build docs
        run: |
          cd docs
          make html
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: docs
          path: docs/_build/html
